export NCCL_P2P_DISABLE=1
CUDA_VISIBLE_DEVICES=1,2,3,5 torchrun --master_port=65432 --nproc_per_node 4 run.py \
    --do_train_first True \
    --do_train_second True \
    --forwardChoose2 2 \
    --output_dir ./stylePrompt_model/stylePrompt_modelA/len1024/e4batch8 \
    --output_dir2 ./stylePrompt_model/stylePrompt_modelB/part50_spc \
    --do_eval True \
    --debug_mode False \
    --learning_rate 1e-4 \
    --learning_rate2 1e-4 \
    --per_device_feature_train_batch_size 2\
    --per_device_feature_dev_batch_size 3 \
    --num_feature_train_epochs 20 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --num_train_epochs 20 \
    --feature_train_data_path ../data/Java_programming/Java_feature2/code_styleFeature_train.json \
    --feature_dev_data_path ../data/Java_programming/Java_feature2/code_styleFeature_dev.json \
    --train_data_path ../data/Java_part_programming50/Java_programming_train.json \
    --eval_data_path ../data/Java_part_programming50/Java_programming_dev.json \
    --continue_train False \
    --enable_contrast True \
    --alpha 0.5